services:
  minio:
    image: bitnami/minio:2024.12.18-debian-12-r0
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: test-bucket
